server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nguleduy/microservice/tree/main/spring-microservice-config-server-repo
          search-paths:
            - fornecedor
            - joseph
            - transportation
