server:
  port: 8081

spring:
  application:
    name: 'spring-microservice-fornecedor'
  datasource:
    url: jdbc:postgresql://localhost:5432/fornecedor
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
