spring:
  datasource:
#    name: db-dev
    url: jdbc:postgresql://localhost:5432/fornecedor
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    platform:
      hikari:
        connection-timeout: 20000
        maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: true
        ddl-auto: update
        temp.use_jdbc_metadata_defaults: false
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
      generate-ddl: true
