server:
  port: 8080

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: 'spring-microservice-joseph'
  boot:
    admin:
      client:
        url:
          - http://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8088/user

hystrix:
  shareSecurityContext: true
